name: Update NBA Players

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update-players:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Generate Prisma Client
        working-directory: backend
        run: npx prisma generate

      - name: Update players
        working-directory: backend
        run: npm run seed:players
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
